run:
	cd docker && docker-compose up --build -d

stop:
	cd docker && docker-compose down

dev_env_logs:
	cd docker && docker-compose logs dev-env

swagger_logs:
	cd docker && docker-compose logs sql_server
